# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 22ee710cf145aefbc03e6dd7fc94ce5515b2d0c593fef8ad92c3a3ce8ec3925800f1aa88e2eff4d688de29ab49c1ec5306c5e83f994fefb05fcad0ed2b2f465a

test:
  secret_key_base: 88477c0ca39316fd18a68403d570c365705d154e81a6fc82c2fa83503151799239307581d689310e11e1f0fcdd9a2c08b0b1a822d12df455f7c04dff4f4b6b00

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
